# .github/workflows/deploy.yaml
# Para no tener que hacer a mano siempre antes de hacer el push el:
# npm run build -> -> -> poner en la linea 23 y 24
# run: cd frontend; npm install; cd ..
# run: cd frontend; npm run build; cd ..
# lo demás no se quita, se deja igual
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - run: npm install

      
      
      
      - run: npm start &

      - run: npm test
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    
      - name: Deploy
        run: gcloud app deploy
